apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fylsg19kz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fylsg19kz-go 
  name: fylsg19kz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fylsg19kz-go 
